---
title: "Research activities"
---

---

##Interests

- Regression models
- Probability and Inference
- Machine Learning
- Discrete-event simulation
- Agent-based simulation

---

##Scientifics events

* __XXVIII Simposio Internacional de Estadística 2018. _(Bucaramanga, Santander).___
    + Correa, A.P; Mesa, A.T.; Ordoñez, J.J.; Castro, J.A.; Usuga, O.C.
"[Cartas de control individual y EWMA para el análisis de la variabilidad en el proceso de deshuese de res de una empresa del sector cárnico](http://ciencias.bogota.unal.edu.co/fileadmin/content/eventos/simposioestadistica/documentos/Simposio_2018/memorias_2018/comunicaciones/Cartas_de_control_individual_y_EWMA_para_el_analisis_de_la_variabilidad_en_el_proceso_de_deshuece_de_res_de_una_empresa_del_sector_carnico_-_Angie_Correa_Sepulveda.pdf)".   

* __XIX Latin-Iberoamerican Conference on Operations Research 2018. _(Lima, Perú).___ 
    + Correa, A.P; Garcés, C.; Castro, J.A.; Ceballos, F.
"Desarrollo de un modelo de simulación de eventos discretos en la producción de suelas termoplásticas".

* __II Congreso Colombiano de Estadística. _(Cali, Colombia).___ 
    + Correa, A.P; Pérez, K.J; Usuga, O.C.
"[Predicción de las categorías del índice de calidad del aire para el Valle de Aburrá](https://drive.google.com/file/d/1oxizkNzxg3xoVmrXTgBVCvYoA3CBj79A/view)".

---

##Shiny apps 

* [Teorema del límite central](https://angiepcorreas.shinyapps.io/Teoremalimitecentral/).

* [Pruebas de hipótesis](https://angiepcorreas.shinyapps.io/Pruebashipotesis/).

* [Pruebas de bondad de ajuste](https://angiepcorreas.shinyapps.io/Pruebas_bondad/).

* [Air quality application for Aburrá Valley (Colombia)](https://angiepcorreas.shinyapps.io/Airqualityapplication/).

---

##Pubs 

* [Pruebas de Bondad de ajuste](http://rpubs.com/angiepcorreas/391417).

---

<center> <p>Copyright &copy; 2018, made with Rmarkdown. All rights reserved.</p> </center>




